def purge(s,myl):
    s = s.replace(" ’ ","'")
    s = s.replace("  "," ")
    s = s.replace("."," .")
    s = s.replace(" . . .", " ")
    s = s.replace(" . . .", " ")
    s = s.replace("-", "")
    s = s.replace("!"," !")
    s = s.replace(",", " ,")
    s = s.replace("?", " ?")
    s = s.replace(' "',' " ')
    s = s.replace('" ', ' " ')
    s = s.replace('"\n', ' "\n')
    s = s.replace("—" ,"")
    s = s.replace("<u>","")
    s = s.replace("</u>", "")
    s = s.replace("<i>","")
    s = s.replace("</i>","")
    s = s.replace("<U>","")
    s = s.replace("</U>","")
    s = s.replace("<b>","")
    s = s.replace("</b>","")
    s = s.replace("<I>","")
    s = s.replace("</I>","")
    s = s.replace("<","")
    s = s.replace(">","")
    s = s.replace("  "," ")
    s = s.replace("  ", " ")
    s = s.replace(" \n","\n")
    while " " == s[0]:
        s = s[1:]
    myl.append(s)
    return myl
def purge(s):
    s = s.replace(" ’ ","'")
    s = s.replace("  "," ")
    s = s.replace("."," .")
    s = s.replace(" . . .", " ")
    s = s.replace(" . . .", " ")
    s = s.replace("-", "")
    s = s.replace("!"," !")
    s = s.replace(",", " ,")
    s = s.replace("?", " ?")
    s = s.replace(' "',' " ')
    s = s.replace('" ', ' " ')
    s = s.replace('"\n', ' "\n')
    s = s.replace("—" ,"")
    s = s.replace("<u>","")
    s = s.replace("</u>", "")
    s = s.replace("<i>","")
    s = s.replace("</i>","")
    s = s.replace("<U>","")
    s = s.replace("</U>","")
    s = s.replace("<b>","")
    s = s.replace("</b>","")
    s = s.replace("<I>","")
    s = s.replace("</I>","")
    s = s.replace("<","")
    s = s.replace(">","")
    s = s.replace("  "," ")
    s = s.replace("  ", " ")
    s = s.replace(" \n","\n")
    while " " == s[0]:
        s = s[1:]
    return s
if __name__ == "__main__":
    new_list = list()
    qlist = list()
    alist = list()

    with open("./cornell/emoclassed/qtagonly/train.q", encoding='utf-8') as f , \
            open("./cornell/emoclassed/qtagonly/train.a", encoding='utf-8') as e:
        for s1,s2 in zip(f,e):
            qlist = purge(s1,qlist)
            alist = purge(s2,alist)
        else:
            print(len(qlist),len(alist))
        print(len(qlist), len(alist))
        f.close()
        e.close()
        qfile = open('./cornell/emoclassed/qtagonly/train.q', 'w+', encoding="UTF-8")
        afile = open('./cornell/emoclassed/qtagonly/train.a', 'w+', encoding="UTF-8")
        qfile.writelines(qlist)
        qfile.close()
        afile.writelines(alist)
        afile.close()